server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:ecommerce_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true

  logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
# Custom application properties
project:
  image: images/
app:
  jwtSecret: mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
  jwtExpirationMs: 3000000
  name: E-commerce Application
  version: 1.0.0